In [2]:
import numpy as np
np.__version__

'1.15.2'

# Arrays

### 1. 배열 값을 명시하여 생성하는 방법

In [9]:
a = np.array([1,2,3]) # 1차원 array [1,2,3] 생성

In [10]:
print(type(a))

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [14]:
print(a.shape)

(3,)


In [13]:
print(a[0], a[1], a[2])

5 2 3


In [18]:
a[0] = 5
a

array([5, 2, 3])

In [21]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(b.shape)

(2, 3)
1 2 4


In [19]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


### 2. 배열 값을 직접 주지 않고 생성하는 방법

1) zeros(n , m) : 모든 값이 0 인 n*m array 생성

In [23]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

2) ones(n , m) : 모든 값이 1 인 n*m array 생성

In [24]:
b = np.ones((1,2))
b

array([[1., 1.]])

3) full((n, m), x) : 모든 값이 x 인 n*m array 생성

In [25]:
c = np.full((2,2), 7)
c

array([[7, 7],
       [7, 7]])

4) eye(n) : n*n 단위행렬 생성

In [27]:
d = np.eye(10)
d

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

5) .random.random((n,m)) : 0 ~ 1의 랜덤 값을 가지는 n*m array 생성

In [35]:
e = np.random.random((10,10))
e

array([[0.55627579, 0.70731906, 0.66136223, 0.91767325, 0.92992803,
        0.25557798, 0.77610798, 0.41325849, 0.94422023, 0.64510991],
       [0.68287355, 0.21781966, 0.31623608, 0.25371124, 0.44573723,
        0.07482875, 0.24653194, 0.24657192, 0.45258456, 0.17048663],
       [0.1322349 , 0.34597744, 0.63140944, 0.96267684, 0.69217019,
        0.96961967, 0.69710371, 0.24042932, 0.67683585, 0.87770315],
       [0.76400555, 0.46824465, 0.42302437, 0.87946358, 0.72099309,
        0.87191065, 0.90847439, 0.61017384, 0.08599083, 0.59004543],
       [0.77669398, 0.16557142, 0.05138731, 0.14754386, 0.52249104,
        0.01694655, 0.54904535, 0.27174223, 0.67101216, 0.58943956],
       [0.43551462, 0.15529789, 0.91676312, 0.17530743, 0.7768135 ,
        0.5011477 , 0.87215113, 0.99571474, 0.73738945, 0.57655837],
       [0.91523246, 0.45801785, 0.49797119, 0.09852252, 0.71154253,
        0.7769387 , 0.25881995, 0.41016056, 0.11381929, 0.60712258],
       [0.12110794, 0.48490603, 0.6438818

---

# Array Slicing

### 배열의 일부를 가져다 오는 방법 
인덱스 영역에서 콜론(:) 사용

In [37]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [40]:
a[0, 1]

2

In [42]:
b[0, 0] = 77
print(a[0, 1])

77


원본을 바꾸기 때문에 원본의 변경을 피하려면 깊은 복사 후 사용해야 함!

---

슬라이싱을 사용했을 경우 shape을 더 크게 가진다

In [47]:
row_r1 = a[1, :]
# 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [48]:
col_r1 = a[:1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[[ 1 77  3  4]] (1, 4)
[[77]
 [ 6]
 [10]] (3, 1)


# Array Indexing

In [53]:
# 2차원 배열(3x2) 생성
# [[ 1 2]
# [ 3 4]
# [ 5 6]]
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [59]:
np.array([a[0, 0], a[1, 1], a[2, 0]])

array([1, 4, 5])

---

In [60]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [63]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [64]:
a[np.arange(4), b] += 10
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

---

# 데이터 타입

In [68]:
x = np.array([1, 2])
x.dtype

dtype('int64')

In [69]:
x = np.array([1.0, 2.0])
x.dtype

dtype('float64')

데이터 타입 명시

In [73]:
x = np.array([1.5, 2.0], dtype=np.int64)
x

array([1, 2])

---

# Array 연산

### 기본 사칙연산

In [74]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64) 
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [78]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [79]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [77]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [80]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [81]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [82]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [83]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [84]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

---

## Dot product

matmul or Dot

In [86]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [88]:
# v · w = 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [89]:
# 매트릭스 / 벡터 곱; [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [91]:
# 매트릭스 / 매트릭스 곱;
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


---

## sum

In [92]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [93]:
print(np.sum(x))
# 모든 원소의 합

10


In [94]:
print(np.sum(x, axis=0)) # 각 열의 합

[4 6]


In [95]:
print(np.sum(x, axis=1)) # 각 행의 합

[3 7]


---

## Transpose

In [98]:
x = np.array([[1, 2], [3, 4]])
x.T

array([[1, 3],
       [2, 4]])

In [99]:
v = np.array([1,2,3])
v.T

array([1, 2, 3])

---

## Broadcasting

In [101]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)

In [103]:
# x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
for i in range(4):
    y[i, :] = x[i, :] + v

In [104]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [105]:
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함

In [106]:
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [107]:
x + vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

---

연습문제 2

In [119]:
v1 = (1, 2)
v2 = (1, 1)
x = 15
y = 25

In [121]:
mat1 = np.array((v1, v2))
a

array([[1, 2],
       [1, 1]])

In [171]:
a[0:,:1]

array([[1],
       [1]])

In [174]:
a[:,:1]


array([[1],
       [1]])

# pickle

In [161]:
import pickle

In [163]:
favor_col = {'lion': 'yellow', "kitty": "red"}
pickle.dump(favor_col, open('save.p',"wb"))

In [164]:
favor_col_opn = pickle.load(open("save.p","rb"))

In [165]:
favor_col_opn

{'kitty': 'red', 'lion': 'yellow'}